// 关系
export const conjunctionOptions = [
  {
    label: '且',
    value: 'and',
    color: '#0832a6',
    background: '#d4e5ff',
    expression: '&&',
  },
  {
    label: '或',
    value: 'or',
    color: '#d46b08',
    background: '#ffd591',
    expression: '||',
  },
];

export const OperatorsOptions: any = {
  text: [
    { label: '等于', value: 'equal' },
    { label: '不等于', value: 'not_equal' },
    { label: '模糊匹配', value: 'like' },
    { label: '不匹配', value: 'not_like' },
    { label: '匹配开头', value: 'starts_with' },
    { label: '匹配结尾', value: 'ends_with' },
    { label: '为空', value: 'is_empty' },
    { label: '不为空', value: 'is_not_empty' },
  ],
  number: [
    { label: '等于', value: 'equal' },
    { label: '不等于', value: 'not_equal' },
    { label: '小于', value: 'less' },
    { label: '小于或等于', value: 'less_or_equal' },
    { label: '大于', value: 'greater' },
    { label: '大于或等于', value: 'greater_or_equal' },
    { label: '属于范围', value: 'between' },
    { label: '不属于范围', value: 'not_between' },
    { label: '为空', value: 'is_empty' },
    { label: '不为空', value: 'is_not_empty' },
  ],
  date: [
    { label: '等于', value: 'equal' },
    { label: '不等于', value: 'not_equal' },
    { label: '小于', value: 'less' },
    { label: '小于或等于', value: 'less_or_equal' },
    { label: '大于', value: 'greater' },
    { label: '大于或等于', value: 'greater_or_equal' },
    { label: '属于范围', value: 'between' },
    { label: '不属于范围', value: 'not_between' },
    { label: '为空', value: 'is_empty' },
    { label: '不为空', value: 'is_not_empty' },
  ],
  time: [
    { label: '等于', value: 'equal' },
    { label: '不等于', value: 'not_equal' },
    { label: '小于', value: 'less' },
    { label: '小于或等于', value: 'less_or_equal' },
    { label: '大于', value: 'greater' },
    { label: '大于或等于', value: 'greater_or_equal' },
    { label: '属于范围', value: 'between' },
    { label: '不属于范围', value: 'not_between' },
    { label: '为空', value: 'is_empty' },
    { label: '不为空', value: 'is_not_empty' },
  ],
  select: [
    { label: '等于', value: 'select_equals' },
    { label: '不等于', value: 'select_not_equals' },
    { label: '包含', value: 'select_any_in' },
    { label: '不包含', value: 'select_not_any_in' },
    { label: '为空', value: 'is_empty' },
    { label: '不为空', value: 'is_not_empty' },
  ],
};
